In [2]:
import sys
import numpy as np

# Broadcasting and Bectorized operations

In [3]:
a = np.arange(4)

In [4]:
a

array([0, 1, 2, 3])

In [5]:
a + 10

array([10, 11, 12, 13])

In [6]:
a * 10

array([ 0, 10, 20, 30])

In [7]:
a += 100

In [8]:
a

array([100, 101, 102, 103])

In [9]:
l = [0, 1, 2, 3]

In [10]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [11]:
a = np.arange(4)

In [12]:
a

array([0, 1, 2, 3])

In [13]:
b = np.array([10, 10, 10, 10])

In [14]:
a + b

array([10, 11, 12, 13])

In [15]:
a * b

array([ 0, 10, 20, 30])

# Boolean arrays
_(also called masks)_