In [13]:
# Import the numpy package under the name np
import numpy as np
import sys

# Print the numpy version and the configuration
print(np.__version__)

1.20.1


# Linear Algebra

In [2]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [3]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [4]:
# Dot product
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [5]:
# Cross product
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [6]:
# Transposing
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [7]:
B

array([[6, 5],
       [4, 3],
       [2, 1]])

In [8]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# Size of objects in Memory

## Int, floats

In [14]:
# An integer in Python is > 24 bytes
sys.getsizeof(1)

28

In [15]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [16]:
10**100

10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [17]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [31]:
# # Numpy size is much smaller
# np.dtype(int8).itemsize

In [18]:
np.dtype(float).itemsize

8

## Lists are even larger

In [20]:
# A one-element list
sys.getsizeof([1])

64

In [21]:
# An array of one element in numpy
np.array([1]).nbytes

4

## And performance is also important

In [32]:
l = list(range(100000))

In [26]:
l

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [33]:
a = np.arange(100000)

In [27]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [35]:
%time sum([x ** 2 for x in l])

Wall time: 88.9 ms


333328333350000

In [34]:
%time np.sum(a ** 2)

Wall time: 1e+03 µs


216474736

## Useful Numpy functions

### **random**

In [37]:
np.random.random(size=2)

array([0.98966014, 0.6049008 ])

In [38]:
np.random.normal(size=2)

array([-1.74344421,  1.01115065])

In [39]:
np.random.rand(2, 4)

array([[0.96378548, 0.39676288, 0.66196366, 0.6512798 ],
       [0.15654684, 0.43136639, 0.94420997, 0.13610593]])

### **arange**

In [40]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [42]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### **reshape**

In [43]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### **linspace**

In [45]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [46]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [47]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### **zeros, ones, empty**

In [51]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [52]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.zeros((3, 3), dtype=np.int)

<ipython-input-53-ef30deaab30c>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((3, 3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [54]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [60]:
np.zeros((3, 3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [56]:
np.zeros((3, 3), dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [61]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [62]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [70]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [71]:
np.empty((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [72]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### **identity** and **eye**

In [73]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [79]:
"Hello World"[6]

'W'

### Exercises: https://github.com/ine-rmotr-curriculum/freecodecamp-intro-to-numpy