### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

In [13]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get Dimention
b.ndim

2

In [8]:
b.shape

(2, 3)

In [11]:
# Get Type
a.dtype

dtype('int16')

In [14]:
# Get Size (in bytes)
a.itemsize

4

In [16]:
# Get total size
a.size

3

In [17]:
# Get total size
a.nbytes

12