### Mathematics

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2

array([2, 4, 6, 8])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [7]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [8]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [9]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [10]:
# Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### For a lot more: (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [20]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [21]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [22]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse
- Etc...

### Statistics

In [23]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.min(stats, axis=0)

array([1, 2, 3])

In [30]:
np.min(stats, axis=1)

array([1, 4])

In [25]:
np.max(stats)

6

In [31]:
np.sum(stats)

21

In [32]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [33]:
np.sum(stats, axis=1)

array([ 6, 15])