### Initializing Differrent Types of Arrays

In [1]:
import numpy as np

In [2]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# All 0s matrix
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [8]:
# Any othe number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Any othe number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [12]:
# Any othe number (full_like)
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [14]:
# Random decimal numbers (between 0 and 1)
np.random.rand(4,2,3)

array([[[8.26716190e-01, 4.90143137e-01, 7.36582979e-01],
        [8.85760331e-01, 1.32437475e-04, 5.33325011e-01]],

       [[6.62827048e-02, 6.88575877e-01, 3.00138140e-01],
        [6.93605376e-01, 9.93426454e-01, 5.26212463e-01]],

       [[9.63821260e-01, 6.14842063e-01, 6.20173657e-02],
        [8.37586990e-02, 2.14440835e-01, 8.37390319e-01]],

       [[8.98977791e-01, 4.64268446e-01, 2.79076287e-01],
        [6.15507099e-01, 1.22890104e-01, 7.72960752e-01]]])

In [16]:
# Random decimal numbers-
np.random.random_sample(a.shape)

array([[0.47619737, 0.20392712, 0.01713809, 0.16044606, 0.94306749,
        0.04854877, 0.86481698],
       [0.21900139, 0.61126082, 0.91491881, 0.98394471, 0.75132348,
        0.73468259, 0.00981578]])

In [17]:
# Random decimal numbers (between 0 and 1)
np.random.rand(4,2)

array([[0.42715211, 0.61045088],
       [0.8463662 , 0.23712638],
       [0.50679864, 0.66867763],
       [0.9810778 , 0.06929983]])

In [27]:
# Random Integer values (0 to n )
n = 10
np.random.randint(n, size=(3,3))

array([[2, 0, 9],
       [9, 8, 9],
       [6, 7, 6]])

In [37]:
# Random Integer values (n1 to n2)
n1 = -4
n2 = 7
np.random.randint(n1,n2, size=(3,3))

array([[ 4,  5,  4],
       [-2,  1, -4],
       [ 5,  3, -2]])

In [39]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
# Repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [49]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [50]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [54]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [55]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [56]:
b = a
b

array([1, 2, 3])

In [57]:
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [58]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [59]:
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]
